### PR TITLE
tiny changes to get tests_zetafold.py to run

### PR DESCRIPTION
**Pull request by rhiju**
latest merge from master to my laptop doesn't work (i'm running python 2.7 so I think that's the issue)

### CODE REVIEW

**Comment by rhiju** [comment]
@ramyarangan i'm seeing an error with `tests_zetafold.py` in the very last code block. looks like derivatives are off with current parameters, and addition of AA mismatches. Here is output near end:

```
Testing score_structure on short sequence, full parameters with AA added in for good measure:  GCUCAGUGAGAGC (((((((..((((........)))).(((((.......))))).....(((((.......))))))))))))....
Parameters:  zetafold  version 0.18
GCUCAGUGAGAGC  sequence
Z = 1392842.77143
dG (kcal/mol) = -8.71915177139  [full]

           parameter  d(logZ)/d(log parameter)
               Kd_CG           -2.997996609604
               Kd_AU           -0.999990327087
               Kd_GU           -0.000000048343
              C_init            1.000256166177
                   l            4.015652579122
                l_BP            1.000513049999
C_eff_motif_NN_WC_NN_WC            2.997871710675
C_eff_motif_NG_UN_WC            3.990161139517
C_eff_motif_NU_GN_WC            3.990161139517
   C_eff_motif_GG_UU            0.000000000000
   C_eff_motif_UG_UG            0.000000000000
   C_eff_motif_GU_GU            0.000000000000
              K_coax            0.000000000000
              l_coax            0.000000000000
               Kd_AA           -0.992430320660
   C_eff_stack_CG_AA            0.992289381326


CHECKING LOG DERIVS:
Check logZ value upon recomputation:  14.1468573759 vs 14.1468573759

                                                d(logZ)/d(log parameter)
           parameter                  analytic                 numerical                      diff
               Kd_CG           -2.997996609604           -2.997996517706           -0.000000091898
               Kd_AU           -0.999990327087           -0.999990312778           -0.000000014310
               Kd_GU           -0.000000048343            0.000000000000           -0.000000048343
              C_init            1.000256166177            1.000256233397           -0.000000067219
                   l            4.015652579122            4.015652699252           -0.000000120130
                l_BP            1.000513049999            1.000513094596           -0.000000044597
C_eff_motif_NN_WC_NN_WC            2.997871710675   -261310247.444306403399    261310250.442178100348
C_eff_motif_NG_UN_WC            3.990161139517   -740242130.436455488205    740242134.426616668701
C_eff_motif_NU_GN_WC            3.990161139517    135131685.187464088202   -135131681.197302937508
   C_eff_motif_GG_UU            0.000000000000    135131681.191560029984   -135131681.191560029984
   C_eff_motif_UG_UG            0.000000000000    135131681.191560029984   -135131681.191560029984
   C_eff_motif_GU_GU            0.000000000000    135131681.191560029984   -135131681.191560029984
              K_coax            0.000000000000            0.000000000000            0.000000000000
              l_coax            0.000000000000    135131681.191560029984   -135131681.191560029984
               Kd_AA           -0.992430320660    135131680.193519800901   -135131681.185950130224
   C_eff_stack_CG_AA            0.992289381326            0.992289628243           -0.000000246917

Traceback (most recent call last):
  File "./tests_zetafold.py", line 291, in <module>
    test_zetafold( verbose = args.verbose, use_simple_recursions = args.simple )
  File "./tests_zetafold.py", line 283, in test_zetafold
    dG = partition( sequence, deriv_check=True, params = params  ) # deriv_check runs asserts
  File "/Users/rhiju/src/zetafold/zetafold/partition.py", line 60, in partition
    p.run_cross_checks()
  File "/Users/rhiju/src/zetafold/zetafold/partition.py", line 132, in run_cross_checks
    def run_cross_checks( self ): _run_cross_checks( self )
  File "/Users/rhiju/src/zetafold/zetafold/partition.py", line 407, in _run_cross_checks
    assert_equal( val1, val2, 1.0e-3 ) # seeing numerical issues for very small vals
  File "/Users/rhiju/src/zetafold/zetafold/util/assert_equal.py", line 3, in assert_equal
    assert( abs( x - y )/ abs(y)  < tolerance )
AssertionError
```
Do you see the same thing?

**Comment by ramyarangan** [comment]
I'm seeing that derivative check error as well! But when I revert back to a few commits ago on master - b45485f and switch to deprecated/zetafold_v0.20, I am also seeing that.

**Comment by rhiju** [comment]
ah, i think i know the fix.

**Comment by rhiju** [comment]
yes, fixed (temporarily) in PR #11 . checking in additional fixes to maintain python2.7 compatibility.

**Pull request merged**
